Auto=read.table("/home/orange/Desktop/Auto.data",header=T,na.strings="?")
fix(Auto)
Auto=na.omit(Auto)
dim(Auto)
Auto=Auto[,-9]
names(Auto)
attach(Auto)
range(Auto)
#fix(Auto)
apply(Auto,2,range)
apply(Auto,2,sd)
apply(Auto,2,mean)
Auto=Auto[-seq(10,85),]
apply(Auto,2,range)
apply(Auto,2,sd)
apply(Auto,2,mean)
dim(Auto)
Auto=read.table("/home/orange/Desktop/Auto.data",header=T,na.strings="?")
Auto=na.omit(Auto)
Auto=Auto[,-9]
dim(Auto)
pdf("/home/orange/Documents/ISLR with Applications in R/2.4.9.pdf")
pairs(Auto)
cor(Auto, method = "pearson", use = "complete.obs")
#install.packages("PerformanceAnalytics")
library("PerformanceAnalytics")
chart.Correlation(Auto, histogram=TRUE)
dev.off()