LoadLibraries=function(){
  library(ISLR)
  library(MASS)
  library(car)
  print("Libraries have been loaded")
}
LoadLibraries()
?Boston
fix(Boston)
lm.fit=lm(medv~lstat,data=Boston)
lm.fit
summary(lm.fit)
names(lm.fit)
pdf("/home/orange/Desktop/Lab 3.pdf")
plot(Boston$lstat,Boston$medv)
abline(lm.fit)
?abline
plot(Boston$lstat,Boston$medv)
abline(lm.fit, lwd=2, col='red')
plot ( Boston$lstat , Boston$medv , col =" red ")
attach(Boston)
plot ( lstat , medv , pch ='+')
plot (1:20 ,1:20 , pch =1:20)
par(mfrow=c(2,2))
plot(lm.fit)
par(mfrow=c(1,1))
plot (predict( lm.fit ) , residuals( lm.fit ) )
plot (predict( lm.fit ) , rstudent( lm.fit ) )
par(mfrow=c(2,2))
plot(lm.fit)
lm.fit = lm(medv~lstat+age, data=Boston)
summary(lm.fit)
plot(lm.fit)
lm.fit = lm(medv~., data=Boston)
summary(lm.fit)
lm.fitinter=lm(medv~lstat*age, data=Boston)
plot(lm.fitinter)
summary(lm.fitinter)
lm.fit2 = lm(medv~lstat+I(lstat^2), data = Boston)
summary(lm.fit2)
lm.fit = lm(medv~lstat, data=Boston)
anova(lm.fit, lm.fit2)
plot(lm.fit2)
lm.fit5=lm(medv~poly(lstat,5),data=Boston)
summary(lm.fit5)
summary(lm(medv~log(rm),data=Boston))
fix(Carseats)
lm.fitc=lm(Sales~.+Income:Advertising+Price:Age,data=Carseats)
summary(lm.fitc)
contrasts(Carseats$Urban)
contrasts(Carseats$ShelveLoc)
?contrasts
dev.off()
